[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".netlify/functions"

# Redirect all requests to the Nuxt app for client-side routing
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/videos/*"
  to = "/videos/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 